version: "3"
services:
  mongo:
    container_name: explore-english-mongo
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: explore-english-app
    image: node:12
    working_dir: /usr/src/app
    restart: always
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./swagger.yml:/usr/src/app/swagger.yml
      - ./package.json:/usr/src/app/package.json
    env_file:
      - ./.env
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/explore-english
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
